name: ci
on: pull_request

env:
  BATON_LOG_LEVEL: debug
  BATON_TOKEN: "${{ secrets.BATON_TOKEN }}"

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m

  test-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-terraform-cloud
        run: go build ./cmd/baton-terraform-cloud
      - name: Grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-terraform-cloud
          baton-entitlement: "team:team-CYFFnmh6HJ4ySPfJ:member"
          baton-principal: "user-DU4i2UFv6Vh7AxUp"
          baton-principal-type: user
