name: ci
on: pull_request

jobs:
  test-teams:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_TOKEN: ${{ secrets.BATON_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-terraform-cloud
        run: go build ./cmd/baton-terraform-cloud
      - name: Grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-terraform-cloud
          baton-entitlement: ${{ vars.BATON_ENTITLEMENT }}
          baton-principal: ${{ vars.BATON_PRINCIPAL }}
          baton-principal-type: user
